### ISSUE TITLE
Add more contributors from projects that contribute to .NET

### ISSUE THREAD

**Issue by JonDouglas** [dotnet/website-thanks-data#19]
There are a number of projects that aren't represented in the thanks data. NuGet is one that has had various internal and community contributions that we outline in [release notes](https://docs.microsoft.com/en-us/nuget/release-notes/nuget-6.0#community-contributions) and there doesn't seem to be a tag for a number of projects in the repos below:

https://github.com/dotnet/core/blob/main/Documentation/core-repos.md

**Comment by mairaw** [comment]
Thanks @JonDouglas. We should look into that. Does NuGet follows the same tagging system as the dotnet repos? e.g. https://github.com/dotnet/runtime/tags

**Comment by mairaw** [comment]
@JonDouglas Can you confirm whether NuGet uses the same release tags as .NET repos?

**Comment by JonDouglas** [comment]
We do not sadly. Sorry I didn't answer earlier. Given we don't support tags right now, I think this issue is moot. Thanks for helping!
