### ISSUE TITLE
Replace globe icon with .NET brand

### ISSUE THREAD

**Issue by deeprobin** [dotnet/website-thanks-data#25]
![image](https://user-images.githubusercontent.com/10373452/166876463-dddb9fb3-65db-417b-8e18-3cdf4a6d449d.png)
I suggest that we replace this globe/Internet icon with the official .NET brand.
Also I suggest to use a separate icon for the preview versions.

For example, Insider versions of Visual Studio Code are green instead of blue. I think a color distinction would be useful here.

**Comment by mairaw** [comment]
Thanks @deeprobin for your feedback. I'll discuss the icon with our design team.

For versions though, we do have plans to eventually move all the contributions to a single entry per major.minor, so we wouldn't need to distinguish previews.

**Comment by jongalloway** [comment]
This was fixed by https://github.com/dotnet/website/issues/4922
