### ISSUE TITLE
.NET Core 1.0.0 RC1 data isn't parsing

### ISSUE THREAD

**Issue by danzhu54** [dotnet/website-thanks-data#27]
The logic needs to be updated for the very first release. Since there aren't any previous release commits to compare it with, we always end up with 0 contributors.

![image](https://user-images.githubusercontent.com/33338258/168342604-f989149c-2a11-42b0-90f8-5098ba45fee2.png)

**Comment by mairaw** [comment]
Is this still true now that we combined everything?

**Comment by danzhu54** [comment]
This is resolved now that we've combined the records
