### ISSUE TITLE
Add 9.0 for previews

### ISSUE THREAD

**Issue by JonDouglas** [dotnet/website-thanks-data#61]
To help thank folks, can we get 9.0 ready by 2/13?

Thank you!

**Comment by mairaw** [comment]
Sure! The data is ingested from https://github.com/dotnet/core/releases. So as soon as that data is updated, we can run our tooling. But probably won't be live by when the blog post goes live. It's usually a few hours later.

**Comment by mairaw** [comment]
Closing since https://dotnet.microsoft.com/en-us/thanks is updated
